### ISSUE TITLE
No reports are collected

### ISSUE THREAD

**Issue by cristi1979** [theforeman/foreman_abrt#4]
This is the configuration for abrt :

cat /etc/libreport/plugins/ureport.conf
    URL = https://foreman.domain.net:8443/abrt
    SSLVerify = no

foreman.domain.net is foreman+foreman_proxy
/etc/foreman-proxy/settings.yml has :foreman_url: https://foreman.domain.net

/etc/foreman-proxy/settings.d/abrt.yml
    ---
    :enabled: true
    :abrt_send_log_file: /var/log/foreman-proxy/abrt-send.log
    :spooldir: /var/spool/foreman-proxy-abrt
    :aggregate_reports: true
:send_period: 1

When I restart foreman-proxy, I get this in abrt.log (I have rubygem-abrt installed):

    ==> /var/log/abrt.log <==
    2015-01-12T18:15:50.663232-05:00 foreman.domain.net abrt[13014]: detected unhandled Ruby exception in '/usr/share/foreman-proxy/bin/smart-proxy'

    backtrace:
    :/usr/share/foreman-proxy/lib/smart_proxy.rb:143:in `join': SIGTERM (SignalException)
    :	from /usr/share/foreman-proxy/lib/smart_proxy.rb:143:in `launch'
    :	from /usr/share/foreman-proxy/bin/smart-proxy:6:in `<main>'

Packages installed:

rpm -qa | grep abrt | sort
    abrt-2.1.11-12.0.1.el7.x86_64
    abrt-addon-ccpp-2.1.11-12.0.1.el7.x86_64
    abrt-addon-kerneloops-2.1.11-12.0.1.el7.x86_64
    abrt-addon-pstoreoops-2.1.11-12.0.1.el7.x86_64
    abrt-addon-python-2.1.11-12.0.1.el7.x86_64
    abrt-addon-vmcore-2.1.11-12.0.1.el7.x86_64
    abrt-addon-xorg-2.1.11-12.0.1.el7.x86_64
    abrt-cli-2.1.11-12.0.1.el7.x86_64
    abrt-console-notification-2.1.11-12.0.1.el7.x86_64
    abrt-libs-2.1.11-12.0.1.el7.x86_64
    abrt-python-2.1.11-12.0.1.el7.x86_64
    abrt-tui-2.1.11-12.0.1.el7.x86_64
    ruby193-rubygem-foreman_abrt-0.0.5-1.el7.noarch
    rubygem-abrt-0.1.0-1.el7.noarch
    rubygem-smart_proxy_abrt-0.0.6-2.el7.noarch

**Comment by mmilata** [comment]
Hm, the unhandled exception might be just the result of systemd restarting the proxy.

When you trigger a crash, does ABRT create a directory in `/var/tmp/abrt`? Some time after the crash, does a new file appear in `/var/spool/foreman-proxy-abrt` on the proxy host? If not, can you run `reporter-ureport -vvv -d /var/tmp/abrt/<the-crash-directory>` and post the output?

**Comment by cristi1979** [comment]
it was something with my configuration. It's working now

**Comment by ohadlevy** [comment]
what was it? just that we know if we should test / enforce / check for this
kind of problems?

**Comment by cristi1979** [comment]
Most probably I wasn't waiting long enough for the reports to be sent. But I'm not certain, because I've reinstalled abrt in the process and after that executed the commands from mmilata. After that I got reports in foreman.

**Comment by mmilata** [comment]
My guess is that ABRT was waiting for sosreport which can run couple of minutes sometimes. For testing you can disable it by commenting the corresponding event in `/etc/libreport/events.d/abrt_event.conf`.

**Comment by ohadlevy** [comment]
should we provide some hints when there are no reports?

**Comment by cristi1979** [comment]
I don't see what hints can be given. Maybe just to explain the flow of events? That was my problem, that I didn't knew what was going on: abrt writes to /var/spool/abrt, events are run on that dir, reporter-ureport sends ureports to foreman proxy, foreman-proxy waits for the cron job to send them to foreman.
