### ISSUE TITLE
please update README to enable epel repository on rhel7 system so that will-crash programs can be utilized for verification

### ISSUE THREAD

**Issue by tkolhar** [theforeman/foreman_abrt#6]
please update README to enable epel repository on rhel7 system so that will-crash programs can be utilized for verification
https://github.com/theforeman/foreman_abrt/blob/master/README.md#verifying-that-the-setup-works

thanks

**Comment by mmilata** [comment]
I've added a paragraph about EPEL in 231a296326852298a7cbe43fe2e8a3c70d5d5158.

Also, I have moved all the information pertaining to the installation on Katello from the `katello-docs` branch to the README in `master` branch. So both instructions for Katello and stand-alone Foreman installations are now in one file.
